# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ControlesBDUniPlugin
                                 A QGIS plugin
 plugin de controles bduni
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-11
        git sha              : $Format:%H$
        copyright            : (C) 2025 by GSchittek
        email                : gabin.schittek@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis import QtCore
from qgis.core import (QgsProject, Qgis, QgsProcessingContext, QgsProcessingFeedback,
                       QgsApplication, QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterFile)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QListWidget, QListWidgetItem, QMessageBox
import sip
import gc


# Import the code for the dialog
from .controles_bduni_plugin_dialog import ControlesBDUniPluginDialog
from .processing_provider import ControlesBDUniProvider
import os.path
import json
from json.decoder import JSONDecodeError
import logging


# Variable globale pour stocker le provider et éviter sa destruction prématurée
_provider_instance = None


class ControlesBDUniPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """

        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ControlesBDUniPlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Controles BDUni Plugin')
        self.provider = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ControlesBDUniPlugin', message)

    def _is_provider_deleted(self):
        """Vérifie si l'objet C++ du provider a été supprimé"""
        if self.provider is None:
            return True
        try:
            return sip.isdeleted(self.provider)
        except:
            return True


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/controles_bduni_plugin/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Controles'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

        # Initialiser et enregistrer le provider de processing via le script
        self.initProcessing()

    def initProcessing(self):
        """Initialise le provider de processing via le script load_controls_processing"""
        global _provider_instance
        import importlib.util

        script_path = os.path.join(self.plugin_dir, 'scripts', 'load_controls_processing.py')
        spec = importlib.util.spec_from_file_location('load_controls_processing', script_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        # Stocker le module pour pouvoir décharger plus tard
        self._load_controls_module = module

        provider = module.load_controles_bduni_processing()
        if provider is not None:
            self.provider = provider
            _provider_instance = provider


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        global _provider_instance

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Controles BDUni Plugin'),
                action)
            self.iface.removeToolBarIcon(action)

        # Désenregistrer le provider via le script
        if hasattr(self, '_load_controls_module'):
            self._load_controls_module.unload_controles_bduni_processing()

        # Nettoyer les références
        self.provider = None
        _provider_instance = None
        gc.collect()


    def run_controls(self):
        controls = []
        layers = []
        for i in range(self.dlg.controlListWidget.count()):
            control_item = self.dlg.controlListWidget.item(i)
            if control_item.checkState() == QtCore.Qt.Checked:
                controls.append(control_item.data(Qt.UserRole))
        for j in range(self.dlg.layerListWidget.count()):
            layer_item = self.dlg.layerListWidget.item(j)
            if layer_item.checkState() == QtCore.Qt.Checked:
                layers.append(QgsProject.instance().mapLayersByName(layer_item.text())[0])
        if not controls:
            self.iface.messageBar().clearWidgets()
            self.iface.messageBar().pushMessage("Erreur", "Aucun contrôle séléctionné", level=Qgis.Warning, duration=10)
            return
        if not layers:
            self.iface.messageBar().clearWidgets()
            self.iface.messageBar().pushMessage("Erreur", "Aucune couche séléctionnée", level=Qgis.Warning, duration=10)
            return

        # Vérifier que le provider est valide
        if self.provider is None or self._is_provider_deleted():
            self.iface.messageBar().pushMessage("Erreur",
                                                "Le provider de contrôles n'est pas disponible. Réinitialisez le plugin.",
                                                level=Qgis.Critical, duration=10)
            return

        for control_name in controls:
            # Chercher l'algorithme dans le provider
            algo = None
            for alg in self.provider.algorithms():
                if alg.__class__.__name__ == control_name:
                    algo = alg
                    break

            if algo is None:
                self.iface.messageBar().pushMessage("Erreur",
                                                    f"Contrôle {control_name} introuvable",
                                                    level=Qgis.Warning, duration=10)
                continue

            try:
                context = QgsProcessingContext()
                feedback = QgsProcessingFeedback()
                json_path = os.path.join(self.plugin_dir, 'param.json')

                # Introspection des paramètres de l'algorithme
                param_defs = algo.parameterDefinitions()
                vector_params = [p for p in param_defs
                                 if isinstance(p, QgsProcessingParameterVectorLayer)]
                has_json = any(isinstance(p, QgsProcessingParameterFile) and p.name() == 'PARAM_JSON'
                               for p in param_defs)

                result = None

                if len(vector_params) == 1:
                    # Cas standard : un seul INPUT_LAYER → exécuter pour chaque couche
                    for layer in layers:
                        params = {vector_params[0].name(): layer}
                        if has_json:
                            params['PARAM_JSON'] = json_path
                        result = algo.processAlgorithm(params, context, feedback)

                elif len(vector_params) > 1:
                    # Cas multi-couches : assigner les couches sélectionnées dans l'ordre des paramètres
                    if len(layers) < len(vector_params):
                        param_names = ', '.join(p.name() for p in vector_params)
                        self.iface.messageBar().pushMessage(
                            "Avertissement",
                            f"{control_name} nécessite {len(vector_params)} couches ({param_names}),"
                            f" seulement {len(layers)} sélectionnée(s)",
                            level=Qgis.Warning, duration=10)
                        continue
                    params = {p.name(): layers[i] for i, p in enumerate(vector_params)}
                    if has_json:
                        params['PARAM_JSON'] = json_path
                    result = algo.processAlgorithm(params, context, feedback)

                if result is not None:
                    self.iface.messageBar().pushMessage("Info",
                        f"Contrôle {control_name} : {result.get('OUTPUT', 'terminé')}",
                        level=Qgis.Info, duration=10)

            except Exception as e:
                logging.basicConfig(level=logging.DEBUG,
                                    filename=os.path.join(self.plugin_dir, 'controls.log'))
                logging.error(f"Erreur pour {control_name}: {e}")
                self.iface.messageBar().pushMessage("Erreur",
                                                    f"Erreur lors de l'exécution de {control_name}: {str(e)}",
                                                    level=Qgis.Warning, duration=10)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False

        try:
            with open(self.plugin_dir+'\param.json', 'r') as file:
                self.param = json.load(file)
        except JSONDecodeError:
            QMessageBox.critical(None,'Erreur','Json de paramétrage invalide')
            return
        except FileNotFoundError:
            QMessageBox.critical(None, 'Erreur', 'Json de paramétrage introuvable')
            return

        self.dlg = ControlesBDUniPluginDialog()
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            try:
                self.run_controls()
            except Exception as e:
                logging.basicConfig(level=logging.DEBUG, filename=self.plugin_dir + '/controls.log')
                logging.debug(e)
                self.iface.messageBar().pushMessage("Warning", str(e), level=Qgis.Warning)
                print(e)
