# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ControlesBDUniPluginDialogParam
                                 A QGIS plugin
 plugin de controles bduni
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-11
        git sha              : $Format:%H$
        copyright            : (C) 2025 by GSchittek
        email                : gabin.schittek@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis import QtCore
from qgis.core import QgsProject, Qgis

from qgis.PyQt.QtWidgets import QAction, QListWidget, QListWidgetItem, QDialog, QTreeWidgetItem

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'controles_bduni_plugin_dialog_param.ui'))


class ControlesBDUniPluginDialogParam(QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ControlesBDUniPluginDialogParam, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.init_signals()


    def init_signals(self):
        return


    def load_json_tree(self, param):
        self.treeWidget.clear()
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setHeaderLabels(["JSON de paramètrage"])

        root_item = QTreeWidgetItem(["Controles"])
        self.treeWidget.addTopLevelItem(root_item)
        self.populate_tree(root_item, param)
        self.treeWidget.expandAll()
        return


    def populate_tree(self, parent, data):
        """
        Recursively populate a QTreeWidgetItem with JSON data.
        """
        if isinstance(data, dict):
            for key, value in data.items():
                item = QTreeWidgetItem([str(key)])
                parent.addChild(item)
                self.populate_tree(item, value)
        elif isinstance(data, list):
            for index, value in enumerate(data):
                item = QTreeWidgetItem([f"[{index}]"])
                parent.addChild(item)
                self.populate_tree(item, value)
        else:
            # Leaf node: show value
            value_item = QTreeWidgetItem([str(data)])
            parent.addChild(value_item)

